env: development
refreshSnapshotInterval: 5
authOpts:
  issuers:
    'https://login.xxxx.com/auth/realms/xxxx':
      wellKnown: https://login.xxxx.com/auth/realms/xxxx/.well-known/openid-configuration
      client:
        clientId: xxx-api
        clientSecret: XXXX
bulletPaths:
- "/bulletPaths"
- "/refreshSnapshotInterval"
- "/authOpts"
